# Generated by Django 5.2.14 on 2026-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('nationality', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('given_name', models.CharField(max_length=60)),
                ('family_name', models.CharField(max_length=60)),
                ('nationality', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['family_name', 'given_name'],
            },
        ),
    ]
