# Generated by Django 5.2.14 on 2026-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
