# Generated by Django 5.2.14 on 2026-05-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('has_sprint', models.BooleanField(default=False)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seasons.circuit')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='seasons.season')),
            ],
            options={
                'ordering': ['season__year', 'number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
