# Generated by Django 5.2.14 on 2026-05-23 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitors', '0002_constructor_url_driver_date_of_birth_driver_url'),
        ('seasons', '0002_round_fp1_at_round_fp2_at_round_fp3_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fp1', 'FP1'), ('fp2', 'FP2'), ('fp3', 'FP3'), ('q', 'Qualifying'), ('sq', 'Sprint Qualifying'), ('sprint', 'Sprint'), ('race', 'Race')], max_length=8)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_sessions', to='seasons.round')),
            ],
            options={
                'ordering': ['round__season__year', 'round__number', 'kind'],
                'unique_together': {('round', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='SessionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastest_lap_seconds', models.FloatField(blank=True, null=True)),
                ('fastest_lap_number', models.IntegerField(blank=True, null=True)),
                ('fastest_lap_compound', models.CharField(blank=True, max_length=12)),
                ('top_speed_kmh', models.FloatField(blank=True, null=True)),
                ('sector1_best_seconds', models.FloatField(blank=True, null=True)),
                ('sector2_best_seconds', models.FloatField(blank=True, null=True)),
                ('sector3_best_seconds', models.FloatField(blank=True, null=True)),
                ('theoretical_best_seconds', models.FloatField(blank=True, null=True)),
                ('laps_completed', models.IntegerField(default=0)),
                ('constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitors.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitors.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='telemetry.session')),
            ],
            options={
                'ordering': ['session', 'fastest_lap_seconds'],
                'indexes': [models.Index(fields=['session', 'top_speed_kmh'], name='telemetry_s_session_720296_idx'), models.Index(fields=['session', 'fastest_lap_seconds'], name='telemetry_s_session_37ad62_idx')],
                'unique_together': {('session', 'driver')},
            },
        ),
    ]
