# Generated by Django 5.2.14 on 2026-05-23 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_constructor_url_driver_date_of_birth_driver_url'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('lap_time_seconds', models.FloatField(blank=True, null=True)),
                ('sector1_seconds', models.FloatField(blank=True, null=True)),
                ('sector2_seconds', models.FloatField(blank=True, null=True)),
                ('sector3_seconds', models.FloatField(blank=True, null=True)),
                ('compound', models.CharField(blank=True, max_length=12)),
                ('tyre_life', models.IntegerField(blank=True, null=True)),
                ('stint_number', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('speed_st_kmh', models.FloatField(blank=True, null=True)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitors.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='telemetry.session')),
            ],
            options={
                'ordering': ['session', 'driver', 'number'],
                'indexes': [models.Index(fields=['session', 'driver', 'number'], name='telemetry_l_session_718a72_idx'), models.Index(fields=['session', 'lap_time_seconds'], name='telemetry_l_session_dcab4a_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'driver', 'number'), name='uniq_lap_session_driver_number')],
            },
        ),
        migrations.CreateModel(
            name='Stint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('compound', models.CharField(blank=True, max_length=12)),
                ('lap_start', models.IntegerField()),
                ('lap_end', models.IntegerField()),
                ('laps_count', models.IntegerField()),
                ('compound_age_at_start', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitors.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stints', to='telemetry.session')),
            ],
            options={
                'ordering': ['session', 'driver', 'number'],
                'indexes': [models.Index(fields=['session', 'driver'], name='telemetry_s_session_053ac8_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'driver', 'number'), name='uniq_stint_session_driver_number')],
            },
        ),
    ]
